export type DefaultAccess = 'everyone' | 'staffOnly' | 'adminOnly' | 'ownerOnly';

export interface CommandDef {
  id: string;
  name: string;
  description: string;
  module: string;
  subcommands: string[];
  defaultAccess: DefaultAccess;
  cooldown?: number;
}

function cmd(name: string, desc: string, module: string, opts?: { subs?: string[]; access?: DefaultAccess }): CommandDef {
  return {
    id: `${module}.${name}`,
    name,
    description: desc,
    module,
    subcommands: opts?.subs ?? [],
    defaultAccess: opts?.access ?? 'everyone',
  };
}

export const COMMAND_REGISTRY: Record<string, CommandDef[]> = {
  core: [
    cmd('report-user', 'Report a user', 'core'),
    cmd('report-bug', 'Report a bug', 'core'),
  ],
  moderation: [
    cmd('ban', 'Permanently ban a member', 'moderation', { access: 'staffOnly' }),
    cmd('tempban', 'Temporarily ban a member', 'moderation', { access: 'staffOnly' }),
    cmd('unban', 'Unban a user', 'moderation', { access: 'staffOnly' }),
    cmd('massban', 'Ban multiple users at once', 'moderation', { access: 'staffOnly' }),
    cmd('banlist', 'View server ban list', 'moderation', { access: 'staffOnly' }),
    cmd('kick', 'Kick a member from the server', 'moderation', { access: 'staffOnly' }),
    cmd('warn', 'Issue a warning', 'moderation', { access: 'staffOnly' }),
    cmd('warnings', 'View warnings for a user', 'moderation', { access: 'staffOnly' }),
    cmd('unwarn', 'Remove a specific warning', 'moderation', { access: 'staffOnly' }),
    cmd('clearwarnings', 'Clear all warnings for a user', 'moderation', { access: 'staffOnly' }),
    cmd('serverwarns', 'View all server warnings', 'moderation', { access: 'staffOnly' }),
    cmd('mute', 'Mute a member', 'moderation', { access: 'staffOnly' }),
    cmd('unmute', 'Unmute a member', 'moderation', { access: 'staffOnly' }),
    cmd('massmute', 'Mute multiple members', 'moderation', { access: 'staffOnly' }),
    cmd('mutelist', 'View active mutes', 'moderation', { access: 'staffOnly' }),
    cmd('lock', 'Lock a channel', 'moderation', { access: 'staffOnly' }),
    cmd('unlock', 'Unlock a channel', 'moderation', { access: 'staffOnly' }),
    cmd('lockdown', 'Lock all channels', 'moderation', { access: 'staffOnly' }),
    cmd('unlockdown', 'Unlock all channels', 'moderation', { access: 'staffOnly' }),
    cmd('slowmode', 'Set channel slowmode', 'moderation', { access: 'staffOnly' }),
    cmd('nuke', 'Clone and delete a channel', 'moderation', { access: 'staffOnly' }),
    cmd('purge', 'Bulk delete messages', 'moderation', { access: 'staffOnly' }),
    cmd('bulkdelete', 'Delete messages by count', 'moderation', { access: 'staffOnly' }),
    cmd('purgeuser', 'Purge messages from a user', 'moderation', { access: 'staffOnly' }),
    cmd('purgebot', 'Purge bot messages', 'moderation', { access: 'staffOnly' }),
    cmd('purgehuman', 'Purge human messages', 'moderation', { access: 'staffOnly' }),
    cmd('history', 'View moderation history', 'moderation', { access: 'staffOnly' }),
    cmd('note', 'Add a note to a user', 'moderation', { access: 'staffOnly' }),
    cmd('userinfo', 'View user information', 'moderation', { access: 'staffOnly' }),
    cmd('softban', 'Ban and immediately unban', 'moderation', { access: 'staffOnly' }),
    cmd('role', 'Add/remove roles from members', 'moderation', { access: 'staffOnly' }),
    cmd('watchlist', 'Add user to watchlist', 'moderation', { access: 'staffOnly' }),
    cmd('altdetect', 'Detect alt accounts', 'moderation', { access: 'staffOnly' }),
    cmd('quarantine', 'Quarantine a member', 'moderation', { access: 'staffOnly' }),
    cmd('unquarantine', 'Remove quarantine', 'moderation', { access: 'staffOnly' }),
    cmd('shadowban', 'Shadow ban a member', 'moderation', { access: 'staffOnly' }),
    cmd('unshadowban', 'Remove shadow ban', 'moderation', { access: 'staffOnly' }),
    cmd('addreputation', 'Add reputation to a user', 'moderation', { access: 'staffOnly' }),
    cmd('removereputation', 'Remove reputation from a user', 'moderation', { access: 'staffOnly' }),
    cmd('setreputation', 'Set a user\'s reputation', 'moderation', { access: 'staffOnly' }),
    cmd('reputationhistory', 'View reputation history', 'moderation', { access: 'staffOnly' }),
    cmd('nickname', 'Change a member\'s nickname', 'moderation', { access: 'staffOnly' }),
    cmd('case', 'View a specific moderation case', 'moderation', { access: 'staffOnly' }),
    cmd('modstats', 'View moderation statistics', 'moderation', { access: 'staffOnly' }),
    cmd('notes', 'View all notes for a user', 'moderation', { access: 'staffOnly' }),
  ],
  automod: [
    cmd('automod', 'View automod settings', 'automod', { access: 'staffOnly' }),
    cmd('testword', 'Test word filter', 'automod', { access: 'staffOnly' }),
    cmd('antilink', 'Anti-link settings', 'automod', { subs: ['toggle', 'whitelist-add', 'whitelist-remove', 'blacklist-add', 'blacklist-remove', 'exempt-channel', 'exempt-role'], access: 'staffOnly' }),
    cmd('wordfilter', 'Word filter settings', 'automod', { subs: ['add-words', 'remove-words', 'add-regex', 'remove-regex', 'list', 'import'], access: 'staffOnly' }),
  ],
  logging: [
    cmd('logchannel', 'Configure channels for logging event types', 'logging', { access: 'staffOnly' }),
    cmd('logconfig', 'View all logging configuration', 'logging', { access: 'staffOnly' }),
    cmd('logignore', 'Exclude channels, roles, or users from logging', 'logging', { access: 'staffOnly' }),
    cmd('logtoggle', 'Toggle logging for specific event types', 'logging', { access: 'staffOnly' }),
    cmd('logs', 'View recent log entries and logging configuration', 'logging', { access: 'staffOnly' }),
  ],
  antiraid: [
    cmd('antiraidconfig', 'Configure anti-raid settings', 'antiraid', { subs: ['view', 'enable', 'disable', 'jointhreshold', 'joinwindow', 'accountage', 'action', 'alertchannel', 'quarantinerole', 'lockdownduration', 'verification'], access: 'staffOnly' }),
    cmd('raidstatus', 'View current raid status', 'antiraid', { access: 'staffOnly' }),
    cmd('raid-lockdown', 'Manually trigger lockdown', 'antiraid', { access: 'staffOnly' }),
    cmd('raid-unlockdown', 'End lockdown', 'antiraid', { access: 'staffOnly' }),
  ],
  leveling: [
    cmd('levels', 'View server level leaderboard', 'leveling'),
    cmd('rank', 'View your or another\'s rank card', 'leveling'),
    cmd('rewards', 'View level-up role rewards', 'leveling'),
    cmd('levelroles', 'Manage level roles', 'leveling', { subs: ['add', 'remove', 'list'], access: 'adminOnly' }),
    cmd('doublexp', 'Toggle double XP events', 'leveling', { subs: ['start', 'stop', 'status'], access: 'adminOnly' }),
    cmd('setxp', 'Set a user\'s XP', 'leveling', { access: 'staffOnly' }),
    cmd('setlevel', 'Set a user\'s level', 'leveling', { access: 'staffOnly' }),
    cmd('resetxp', 'Reset a user\'s XP', 'leveling', { access: 'staffOnly' }),
    cmd('xpmultiplier', 'Manage XP multipliers', 'leveling', { subs: ['set', 'remove', 'list'], access: 'adminOnly' }),
    cmd('noxproles', 'Roles that earn no XP', 'leveling', { subs: ['add', 'remove', 'list'], access: 'adminOnly' }),
    cmd('levelconfig', 'Configure leveling', 'leveling', { subs: ['xp-range', 'cooldown', 'voice-xp', 'announce', 'announce-message', 'stack-roles'], access: 'adminOnly' }),
    cmd('cardstyle', 'Set rank card style', 'leveling'),
    cmd('cardbg', 'Set rank card background', 'leveling'),
  ],
  welcome: [
    cmd('welcometest', 'Preview welcome message', 'welcome', { access: 'adminOnly' }),
    cmd('membercount', 'View member count', 'welcome'),
    cmd('welcome', 'Configure welcome messages', 'welcome', { subs: ['toggle', 'channel', 'message', 'embed', 'embed-color', 'embed-title', 'embed-footer', 'embed-thumbnail', 'image', 'image-background'], access: 'adminOnly' }),
    cmd('welcome-config', 'View welcome config', 'welcome', { subs: ['view', 'toggle'], access: 'adminOnly' }),
    cmd('greet', 'Greeting settings', 'welcome', { subs: ['toggle', 'channel', 'message'], access: 'adminOnly' }),
    cmd('leave', 'Leave message settings', 'welcome', { subs: ['toggle', 'channel', 'message', 'embed', 'embed-color', 'embed-title'], access: 'adminOnly' }),
    cmd('welcomedm', 'Welcome DM settings', 'welcome', { subs: ['toggle', 'message', 'embed'], access: 'adminOnly' }),
    cmd('autorole', 'Auto role settings', 'welcome', { subs: ['toggle', 'add', 'remove', 'add-bot', 'remove-bot', 'delay', 'list'], access: 'adminOnly' }),
    cmd('screening', 'Membership screening', 'welcome', { subs: ['toggle', 'role', 'message'], access: 'adminOnly' }),
    cmd('joingate', 'Join gate settings', 'welcome', { subs: ['toggle', 'min-age', 'action', 'verify-channel', 'log-kicks'], access: 'adminOnly' }),
  ],
  tickets: [
    cmd('ticket', 'Create a new ticket', 'tickets'),
    cmd('close', 'Close a ticket', 'tickets', { access: 'staffOnly' }),
    cmd('ticket-add', 'Add a user to a ticket', 'tickets', { access: 'staffOnly' }),
    cmd('ticket-remove', 'Remove a user from a ticket', 'tickets', { access: 'staffOnly' }),
    cmd('ticket-rename', 'Rename a ticket', 'tickets', { access: 'staffOnly' }),
    cmd('claim', 'Claim a ticket', 'tickets', { access: 'staffOnly' }),
    cmd('transfer', 'Transfer a ticket to another staff', 'tickets', { access: 'staffOnly' }),
    cmd('priority', 'Set ticket priority', 'tickets', { access: 'staffOnly' }),
    cmd('panellist', 'List ticket panels', 'tickets', { access: 'staffOnly' }),
    cmd('ticketpanel', 'Create a ticket panel', 'tickets', { access: 'adminOnly' }),
    cmd('paneledit', 'Edit a ticket panel', 'tickets', { access: 'adminOnly' }),
    cmd('transcript', 'Generate ticket transcript', 'tickets', { access: 'staffOnly' }),
    cmd('transcriptlog', 'View transcript log', 'tickets', { access: 'staffOnly' }),
    cmd('ticket-notice', 'Add a staff notice to ticket', 'tickets', { access: 'staffOnly' }),
    cmd('ticket-config', 'Configure ticket system', 'tickets', { subs: ['view', 'max-tickets', 'auto-close', 'close-behavior', 'claim-toggle', 'priority-toggle', 'transcript-toggle', 'feedback-toggle', 'log-channel', 'add-category', 'remove-category', 'edit-category', 'staff-role', 'naming-format', 'welcome-message'], access: 'adminOnly' }),
    cmd('ticket-staffrole', 'Manage staff roles', 'tickets', { subs: ['add', 'remove', 'list'], access: 'adminOnly' }),
    cmd('ticket-stats', 'View ticket statistics', 'tickets', { access: 'staffOnly' }),
    cmd('ticket-feedback', 'Feedback settings', 'tickets', { subs: ['toggle', 'view'], access: 'adminOnly' }),
  ],
  music: [
    cmd('play', 'Play a song or playlist', 'music'),
    cmd('pause', 'Pause playback', 'music'),
    cmd('resume', 'Resume playback', 'music'),
    cmd('stop', 'Stop and clear queue', 'music'),
    cmd('skip', 'Skip current track', 'music'),
    cmd('previous', 'Play previous track', 'music'),
    cmd('nowplaying', 'Show current track', 'music'),
    cmd('seek', 'Seek to position', 'music'),
    cmd('queue', 'View the queue', 'music'),
    cmd('clear', 'Clear the queue', 'music'),
    cmd('remove', 'Remove a track from queue', 'music'),
    cmd('move', 'Move a track in queue', 'music'),
    cmd('skipto', 'Skip to a specific track', 'music'),
    cmd('shuffle', 'Shuffle the queue', 'music'),
    cmd('loop', 'Toggle loop mode', 'music'),
    cmd('volume', 'Set playback volume', 'music'),
    cmd('filters', 'Audio filter settings', 'music'),
    cmd('voteskip', 'Start a vote skip', 'music'),
    cmd('autoplay', 'Toggle auto-play', 'music'),
    cmd('playlist', 'Manage personal playlists', 'music'),
    cmd('serverplaylist', 'Manage server playlists', 'music'),
    cmd('favorites', 'Manage favorite tracks', 'music'),
    cmd('songinfo', 'View song details', 'music'),
    cmd('lyrics', 'View song lyrics', 'music'),
    cmd('musicconfig', 'Music configuration', 'music', { access: 'adminOnly' }),
    cmd('forceplay', 'Force play a track now', 'music', { access: 'staffOnly' }),
    cmd('djrole', 'Set the DJ role', 'music', { access: 'adminOnly' }),
    cmd('radio-play', 'Play a radio station', 'music'),
    cmd('radio-stop', 'Stop radio', 'music'),
    cmd('radio-list', 'List radio stations', 'music'),
  ],
  currency: [
    cmd('balance', 'View your currency balance or another user\'s balance', 'currency'),
    cmd('daily', 'Claim your daily currency reward', 'currency'),
    cmd('weekly', 'Claim your weekly currency reward', 'currency'),
    cmd('pay', 'Transfer currency to another user', 'currency'),
    cmd('economy', 'View the server economy overview', 'currency'),
    cmd('richest', 'View the richest users in the server', 'currency'),
    cmd('currency-give', 'Give currency to a user', 'currency', { access: 'staffOnly' }),
    cmd('currency-take', 'Remove currency from a user', 'currency', { access: 'staffOnly' }),
    cmd('currency-setbalance', 'Set exact currency balance for a user', 'currency', { access: 'staffOnly' }),
    cmd('currency-reset', 'Reset all currency balances to 0 for a user', 'currency', { access: 'staffOnly' }),
    cmd('currency-config', 'Configure currency settings', 'currency', { access: 'adminOnly' }),
    cmd('currency-audit', 'View transaction history for a user', 'currency', { access: 'staffOnly' }),
    cmd('bank-deposit', 'Deposit coins into your bank', 'currency'),
    cmd('bank-withdraw', 'Withdraw coins from your bank', 'currency'),
    cmd('bank-balance', 'View bank and savings balances', 'currency'),
    cmd('bank-savings', 'Deposit into savings account', 'currency', { subs: ['deposit', 'check', 'collect'] }),
    cmd('bank-collect', 'Collect matured savings with interest', 'currency'),
    cmd('bank-upgrade', 'Upgrade your deposit limit', 'currency'),
    cmd('earn-beg', 'Beg for coins', 'currency'),
    cmd('earn-fish', 'Go fishing for coins', 'currency'),
    cmd('earn-hunt', 'Hunt for coins', 'currency'),
    cmd('earn-crime', 'Commit a crime for coins', 'currency'),
    cmd('earn-rob', 'Rob another user\'s wallet', 'currency'),
    cmd('earn-dig', 'Dig for buried treasure', 'currency'),
    cmd('earn-search', 'Search for coins in random locations', 'currency'),
    cmd('earn-monthly', 'Claim monthly bonus', 'currency'),
    cmd('job-apply', 'Apply for a job', 'currency'),
    cmd('job-work', 'Complete a work shift', 'currency'),
    cmd('job-info', 'View your job info', 'currency'),
    cmd('job-quit', 'Quit your current job', 'currency'),
    cmd('job-list', 'View available jobs', 'currency'),
    cmd('job-leaderboard', 'Top earners leaderboard', 'currency'),
  ],
  shop: [
    cmd('shop', 'Browse the server shop', 'shop'),
    cmd('buy', 'Buy an item', 'shop'),
    cmd('use', 'Use an item from inventory', 'shop'),
    cmd('inventory', 'View your inventory', 'shop'),
    cmd('shop-config', 'Configure the shop', 'shop', { subs: ['view', 'currency', 'tax', 'max-items', 'log-channel', 'show-out-of-stock', 'refunds', 'refund-percent', 'toggle'], access: 'adminOnly' }),
    cmd('shop-add', 'Add an item to the shop', 'shop', { access: 'adminOnly' }),
    cmd('shop-edit', 'Edit a shop item', 'shop', { subs: ['price', 'stock', 'description', 'toggle', 'max-per-user', 'requirement'], access: 'adminOnly' }),
    cmd('shop-remove', 'Remove a shop item', 'shop', { access: 'adminOnly' }),
  ],
  casino: [
    cmd('blackjack', 'Play blackjack against the dealer', 'casino'),
    cmd('slots', 'Spin the slot machine', 'casino'),
    cmd('crash', 'Bet on a rising multiplier', 'casino'),
    cmd('roulette', 'Bet on the roulette wheel', 'casino'),
    cmd('coinflip', 'Flip a coin heads or tails', 'casino'),
    cmd('poker', 'Play video poker', 'casino'),
    cmd('wheel', 'Spin the wheel of fortune', 'casino'),
    cmd('scratchcard', 'Scratch a card for prizes', 'casino'),
    cmd('horserace', 'Bet on horse racing', 'casino'),
    cmd('highlow', 'Higher or lower card game', 'casino'),
    cmd('casino-config', 'Configure casino settings', 'casino', { access: 'staffOnly' }),
  ],
  fun: [
    cmd('wouldyourather', 'Would you rather game', 'fun'),
    cmd('blackjack', 'Play blackjack', 'fun'),
    cmd('wordle', 'Play wordle', 'fun', { subs: ['start', 'guess'] }),
    cmd('trivia', 'Trivia quiz', 'fun'),
    cmd('tictactoe', 'Tic tac toe game', 'fun'),
    cmd('rps', 'Rock paper scissors', 'fun'),
    cmd('roll', 'Roll dice', 'fun'),
    cmd('connect4', 'Connect 4 game', 'fun'),
    cmd('hug', 'Hug someone', 'fun'),
    cmd('pat', 'Pat someone', 'fun'),
    cmd('pout', 'Pout at someone', 'fun'),
    cmd('wave', 'Wave at someone', 'fun'),
    cmd('poke', 'Poke someone', 'fun'),
    cmd('bite', 'Bite someone', 'fun'),
    cmd('dance', 'Dance emote', 'fun'),
    cmd('boop', 'Boop someone', 'fun'),
    cmd('punch', 'Punch someone', 'fun'),
    cmd('laugh', 'Laugh emote', 'fun'),
    cmd('highfive', 'High five someone', 'fun'),
    cmd('kick-fun', 'Fun kick emote', 'fun'),
    cmd('slap', 'Slap someone', 'fun'),
    cmd('kiss', 'Kiss someone', 'fun'),
    cmd('cry', 'Cry emote', 'fun'),
    cmd('cuddle', 'Cuddle someone', 'fun'),
    cmd('compliment', 'Give a compliment', 'fun'),
    cmd('fact', 'Random fun fact', 'fun'),
    cmd('roast', 'Roast someone', 'fun'),
    cmd('meme', 'Random meme', 'fun'),
    cmd('quote', 'Random quote', 'fun'),
    cmd('dog', 'Random dog image', 'fun'),
    cmd('cat', 'Random cat image', 'fun'),
    cmd('joke', 'Random joke', 'fun'),
    cmd('guess', 'Number guessing game', 'fun'),
    cmd('hangman', 'Play hangman', 'fun'),
    cmd('tord', 'Truth or dare', 'fun'),
    cmd('wordchain', 'Word chain game', 'fun'),
    cmd('snake', 'Play snake', 'fun'),
    cmd('fasttype', 'Typing speed challenge', 'fun'),
    cmd('memory', 'Memory match game', 'fun'),
    cmd('reaction', 'Reaction speed test', 'fun'),
    cmd('mathrace', 'Math race game', 'fun'),
    cmd('scramble', 'Word scramble', 'fun'),
    cmd('quizbowl', 'Extended quiz', 'fun'),
    cmd('puzzle', 'Number slide puzzle', 'fun'),
    cmd('highlow', 'Higher or lower cards', 'fun'),
    cmd('duel', 'PvP duel challenge', 'fun'),
    cmd('activity', 'Launch Discord activity', 'fun'),
    cmd('ascii', 'Convert text to ASCII art', 'fun'),
    cmd('say', 'Echo a message', 'fun', { access: 'staffOnly' }),
    cmd('reverse', 'Reverse text', 'fun'),
    cmd('emojify', 'Convert text to emojis', 'fun'),
    cmd('rate', 'Rate anything 0-10', 'fun'),
    cmd('ship', 'Ship two users', 'fun'),
    cmd('hack', 'Fake hacking animation', 'fun'),
    cmd('birdfact', 'Random bird fact', 'fun'),
    cmd('pandafact', 'Random panda fact', 'fun'),
    cmd('fox', 'Random fox image', 'fun'),
  ],
  giveaways: [
    cmd('giveaway-config', 'Configure giveaways', 'giveaways', { subs: ['view', 'channel', 'emoji', 'buttons', 'dm-winners', 'ping-role', 'color', 'end-action', 'max-active', 'self-entry'], access: 'staffOnly' }),
    cmd('gschedule', 'Schedule a giveaway', 'giveaways', { access: 'staffOnly' }),
    cmd('drop', 'Create an instant giveaway', 'giveaways', { access: 'staffOnly' }),
    cmd('glist', 'List active giveaways', 'giveaways'),
    cmd('greroll', 'Reroll a giveaway winner', 'giveaways', { access: 'staffOnly' }),
    cmd('gcancel', 'Cancel a giveaway', 'giveaways', { access: 'staffOnly' }),
  ],
  counting: [
    cmd('counting', 'View counting status', 'counting'),
    cmd('counting-config', 'Configure counting', 'counting', { access: 'adminOnly' }),
  ],
  afk: [
    cmd('afk', 'Set your AFK status', 'afk'),
    cmd('afklist', 'View AFK members', 'afk'),
    cmd('afk-config', 'Configure AFK system', 'afk', { subs: ['view', 'toggle', 'max-length', 'dm-pings', 'max-pings', 'auto-remove', 'log-channel'], access: 'adminOnly' }),
    cmd('afk-remove', 'Remove someone\'s AFK', 'afk', { subs: ['user'], access: 'staffOnly' }),
    cmd('afk-ban', 'Ban user from AFK', 'afk', { subs: ['ban', 'unban', 'list'], access: 'staffOnly' }),
  ],
  aichatbot: [
    cmd('ask', 'Ask the AI a question', 'aichatbot'),
    cmd('aiclear', 'Clear AI conversation history', 'aichatbot'),
    cmd('aiconfig', 'Configure AI chatbot', 'aichatbot', { access: 'adminOnly' }),
    cmd('aichannel', 'Set AI channel', 'aichatbot', { access: 'adminOnly' }),
    cmd('aipersona', 'Set AI persona', 'aichatbot', { access: 'adminOnly' }),
  ],
  activitytracking: [
    cmd('inactivelist', 'View inactive members', 'activitytracking', { access: 'staffOnly' }),
    cmd('activityconfig', 'Configure activity tracking', 'activitytracking', { subs: ['view', 'excludechannel', 'excluderole', 'threshold'], access: 'adminOnly' }),
  ],
  messagetracking: [
    cmd('snipe', 'View last deleted message', 'messagetracking'),
    cmd('editsnipe', 'View last edited message', 'messagetracking'),
    cmd('messagetrackconfig', 'Configure message tracking', 'messagetracking', { subs: ['view', 'logchannel', 'snipe', 'ghostping', 'ignorechannel'], access: 'adminOnly' }),
  ],
  invitetracker: [
    cmd('invites', 'View invite stats', 'invitetracker'),
    cmd('invite-leaderboard', 'Invite leaderboard', 'invitetracker'),
    cmd('invite-config', 'Configure invite tracker', 'invitetracker', { subs: ['view', 'toggle', 'track-leaves', 'track-fakes', 'fake-age', 'fake-leave-hours', 'log-channel', 'announce'], access: 'adminOnly' }),
    cmd('invite-reset', 'Reset invite counts', 'invitetracker', { subs: ['user', 'all'], access: 'staffOnly' }),
    cmd('invite-bonus', 'Manage invite bonuses', 'invitetracker', { subs: ['add', 'remove', 'view'], access: 'staffOnly' }),
  ],
  suggestions: [
    cmd('suggest', 'Submit a suggestion', 'suggestions'),
    cmd('suggestion-config', 'Configure suggestions', 'suggestions', { subs: ['view', 'channel', 'anonymous', 'emojis', 'thread', 'require-reason', 'dm-notify', 'editing', 'colors'], access: 'adminOnly' }),
    cmd('suggestion-approve', 'Approve a suggestion', 'suggestions', { access: 'staffOnly' }),
    cmd('suggestion-consider', 'Mark as considering', 'suggestions', { access: 'staffOnly' }),
    cmd('suggestion-deny', 'Deny a suggestion', 'suggestions', { access: 'staffOnly' }),
    cmd('suggestion-remove', 'Remove a suggestion', 'suggestions', { access: 'staffOnly' }),
    cmd('suggestion-implement', 'Mark as implemented', 'suggestions', { access: 'staffOnly' }),
  ],
  polls: [
    cmd('poll', 'Create a poll', 'polls'),
    cmd('quickpoll', 'Create a quick yes/no poll', 'polls'),
    cmd('pollresults', 'View poll results', 'polls'),
    cmd('pollend', 'End a poll early', 'polls', { access: 'staffOnly' }),
    cmd('poll-config', 'Configure polls', 'polls', { subs: ['view', 'anonymous', 'live-results', 'max-votes', 'max-options', 'max-duration'], access: 'adminOnly' }),
  ],
  forms: [
    cmd('form', 'Fill out a form', 'forms'),
    cmd('formresponses', 'View form responses', 'forms', { access: 'staffOnly' }),
    cmd('formconfig', 'Configure forms', 'forms', { subs: ['view', 'enable', 'disable', 'toggleapproval', 'setnotificationchannel'], access: 'adminOnly' }),
    cmd('formcreate', 'Create a new form', 'forms', { access: 'adminOnly' }),
    cmd('formedit', 'Edit a form', 'forms', { subs: ['addquestion', 'removequestion', 'viewquestions', 'updatemeta'], access: 'adminOnly' }),
    cmd('formdelete', 'Delete a form', 'forms', { access: 'adminOnly' }),
    cmd('formtoggle', 'Enable/disable a form', 'forms', { access: 'adminOnly' }),
    cmd('formreview', 'Review form submissions', 'forms', { access: 'staffOnly' }),
  ],
  autoroles: [
    cmd('autoroleconfig', 'Configure auto roles', 'autoroles', { subs: ['view', 'persistent', 'ignorebots', 'logchannel', 'stackroles'], access: 'adminOnly' }),
    cmd('autorolelist', 'List auto roles', 'autoroles'),
    cmd('autoroleadd', 'Add an auto role', 'autoroles', { access: 'adminOnly' }),
    cmd('autoroleedit', 'Edit an auto role', 'autoroles', { access: 'adminOnly' }),
    cmd('autoroledelete', 'Delete an auto role', 'autoroles', { access: 'adminOnly' }),
    cmd('autoroleclear', 'Clear all auto roles', 'autoroles', { access: 'adminOnly' }),
    cmd('myroles', 'View your roles', 'autoroles'),
  ],
  reputation: [
    cmd('setrep', 'Set reputation', 'reputation'),
    cmd('repconfig', 'Configure reputation', 'reputation', { subs: ['view', 'defaultrep'], access: 'adminOnly' }),
  ],
  colorroles: [
    cmd('color', 'Set your color', 'colorroles'),
    cmd('colorinfo', 'View color info', 'colorroles'),
    cmd('colorlist', 'List available colors', 'colorroles'),
    cmd('colorremove', 'Remove your color', 'colorroles'),
    cmd('colorrandom', 'Get a random color', 'colorroles'),
    cmd('colorconfig', 'Configure color roles', 'colorroles', { subs: ['view', 'joincolor', 'channel', 'reactionmessages', 'deleteresponses', 'overlapwarning', 'maxcolors', 'managementrole', 'whitelist', 'anchor'], access: 'adminOnly' }),
    cmd('coloradd', 'Add a color role', 'colorroles', { access: 'adminOnly' }),
    cmd('coloredit', 'Edit a color role', 'colorroles', { access: 'adminOnly' }),
    cmd('colordelete', 'Delete a color role', 'colorroles', { access: 'adminOnly' }),
    cmd('colorexport', 'Export color config', 'colorroles', { access: 'adminOnly' }),
    cmd('colorimport', 'Import color config', 'colorroles', { access: 'adminOnly' }),
  ],
  quoteboard: [
    cmd('board', 'View the quote board', 'quoteboard'),
    cmd('random-star', 'Random starred message', 'quoteboard'),
    cmd('board-config', 'Configure quote board', 'quoteboard', { subs: ['view', 'create', 'delete', 'threshold', 'self-react', 'nsfw', 'ignore-channel', 'ignore-role', 'color'], access: 'adminOnly' }),
  ],
  leaderboards: [
    cmd('leaderboard', 'View leaderboards', 'leaderboards'),
    cmd('top', 'View top members', 'leaderboards'),
    cmd('leaderboard-config', 'Configure leaderboards', 'leaderboards', { subs: ['view', 'default-type', 'entries', 'rank-card', 'toggle-type'], access: 'adminOnly' }),
  ],
  scheduledmessages: [
    cmd('schedule', 'Schedule a message', 'scheduledmessages', { access: 'staffOnly' }),
    cmd('scheduleedit', 'Edit a scheduled message', 'scheduledmessages', { access: 'staffOnly' }),
    cmd('scheduledelete', 'Delete a scheduled message', 'scheduledmessages', { access: 'staffOnly' }),
    cmd('schedulelist', 'List scheduled messages', 'scheduledmessages', { access: 'staffOnly' }),
    cmd('scheduleconfig', 'Configure scheduling', 'scheduledmessages', { subs: ['view', 'set'], access: 'adminOnly' }),
  ],
  customcommands: [
    cmd('ccreate', 'Create a custom command', 'customcommands', { access: 'adminOnly' }),
    cmd('cedit', 'Edit a custom command', 'customcommands', { access: 'adminOnly' }),
    cmd('cdelete', 'Delete a custom command', 'customcommands', { access: 'adminOnly' }),
    cmd('clist', 'List custom commands', 'customcommands'),
    cmd('cconfig', 'Configure custom commands', 'customcommands', { subs: ['view', 'set'], access: 'adminOnly' }),
    cmd('cvariables', 'View available variables', 'customcommands'),
  ],
  stickymessages: [
    cmd('stick', 'Stick a message', 'stickymessages', { access: 'staffOnly' }),
    cmd('unstick', 'Unstick a message', 'stickymessages', { access: 'staffOnly' }),
    cmd('stickyedit', 'Edit a sticky message', 'stickymessages', { access: 'staffOnly' }),
    cmd('sticky-config', 'Configure sticky messages', 'stickymessages', { access: 'adminOnly' }),
  ],
  statschannels: [
    cmd('statsconfig', 'Configure stats channels', 'statschannels', { subs: ['view', 'interval', 'format', 'categoryname', 'goal'], access: 'adminOnly' }),
    cmd('statsedit', 'Edit a stats channel', 'statschannels', { access: 'adminOnly' }),
    cmd('statscreate', 'Create a stats channel', 'statschannels', { access: 'adminOnly' }),
    cmd('statsdelete', 'Delete a stats channel', 'statschannels', { access: 'adminOnly' }),
    cmd('statslist', 'List stats channels', 'statschannels'),
  ],
  tempvoice: [
    cmd('vcconfig', 'Configure temp voice', 'tempvoice', { subs: ['view', 'enable', 'disable', 'creator', 'category', 'maxvcs', 'cooldown', 'deleteempty', 'inactivity'], access: 'adminOnly' }),
    cmd('vcban', 'Ban from temp voice', 'tempvoice', { access: 'staffOnly' }),
    cmd('vcunban', 'Unban from temp voice', 'tempvoice', { access: 'staffOnly' }),
    cmd('vcforceclose', 'Force close a temp VC', 'tempvoice', { access: 'staffOnly' }),
  ],
  reminders: [
    cmd('remind', 'Set a reminder for a specific time', 'reminders'),
    cmd('reminders', 'View all your active reminders', 'reminders'),
    cmd('remind-repeat', 'Set a recurring reminder', 'reminders'),
    cmd('reminder-cancel', 'Cancel a reminder by ID', 'reminders'),
    cmd('snooze', 'Snooze a recently fired reminder', 'reminders'),
  ],
  translation: [
    cmd('translate', 'Translate text', 'translation'),
    cmd('translatelast', 'Translate last message', 'translation'),
    cmd('languages', 'View supported languages', 'translation'),
    cmd('translateconfig', 'Configure translation', 'translation', { subs: ['view', 'provider', 'libreurl', 'flagreactions', 'defaultlang', 'webhooks', 'cooldown'], access: 'adminOnly' }),
    cmd('translatechannel', 'Set auto-translate channel', 'translation', { access: 'adminOnly' }),
    cmd('translateremove', 'Remove auto-translate', 'translation', { access: 'adminOnly' }),
  ],
  reactionroles: [
    cmd('reactionrole', 'Create a new reaction role panel', 'reactionroles', { access: 'adminOnly' }),
    cmd('rr-button', 'Create a quick button-based reaction role panel', 'reactionroles', { access: 'adminOnly' }),
    cmd('rr-list', 'List all reaction role panels in this server', 'reactionroles'),
    cmd('rr-edit', 'Edit a reaction role panel', 'reactionroles', { access: 'adminOnly' }),
    cmd('rr-remove', 'Delete a reaction role panel', 'reactionroles', { access: 'adminOnly' }),
    cmd('rr-config', 'Manage reaction role settings', 'reactionroles', { access: 'adminOnly' }),
  ],
  birthdays: [
    cmd('birthday', 'Set your birthday', 'birthdays'),
    cmd('birthdayview', 'View someone\'s birthday', 'birthdays'),
    cmd('birthdaylist', 'Show all birthdays in a specific month', 'birthdays'),
    cmd('birthdayupcoming', 'Show upcoming birthdays in this server', 'birthdays'),
    cmd('birthdayannounce', 'Manually trigger a birthday announcement (staff only)', 'birthdays', { access: 'staffOnly' }),
    cmd('birthdayconfig', 'Configure birthday module settings (staff only)', 'birthdays', { access: 'adminOnly' }),
    cmd('birthdayremove', 'Remove a user\'s birthday (staff only)', 'birthdays', { access: 'staffOnly' }),
  ],
  confessions: [
    cmd('confess', 'Submit an anonymous confession', 'confessions'),
    cmd('confession-approve', 'Approve a pending confession', 'confessions', { access: 'staffOnly' }),
    cmd('confession-deny', 'Deny a pending confession', 'confessions', { access: 'staffOnly' }),
    cmd('confession-ban', 'Ban or unban users from confessions', 'confessions', { access: 'staffOnly' }),
    cmd('confession-config', 'Configure confessions module', 'confessions', { access: 'adminOnly' }),
    cmd('confession-reveal', 'Reveal the author of a confession (owner only)', 'confessions', { access: 'ownerOnly' }),
  ],
  profile: [
    cmd('profile-view', 'View a user\'s profile', 'profile'),
    cmd('profile-create', 'Create your profile', 'profile'),
    cmd('profile-delete', 'Delete your profile', 'profile'),
    cmd('profile-aboutme', 'Set your about me', 'profile'),
    cmd('profile-age', 'Set your age', 'profile'),
    cmd('profile-gender', 'Set your gender', 'profile'),
    cmd('profile-location', 'Set your location', 'profile'),
    cmd('profile-status', 'Set your status', 'profile'),
    cmd('profile-birthday', 'Set your birthday', 'profile'),
    cmd('profile-color', 'Set profile embed color', 'profile'),
    cmd('profile-banner', 'Set banner image', 'profile'),
    cmd('profile-add', 'Add to a favorites list', 'profile'),
    cmd('profile-remove', 'Remove from a favorites list', 'profile'),
    cmd('profile-config', 'Configure profile settings', 'profile', { access: 'staffOnly' }),
  ],
  family: [
    cmd('family-propose', 'Propose marriage', 'family'),
    cmd('family-adopt', 'Adopt a user as your child', 'family'),
    cmd('family-divorce', 'Divorce your partner', 'family'),
    cmd('family-disown', 'Disown a child', 'family'),
    cmd('family-tree', 'View family tree', 'family'),
    cmd('family-partner', 'View partner info', 'family'),
    cmd('family-children', 'View children list', 'family'),
    cmd('family-family', 'View full family overview', 'family'),
    cmd('family-config', 'Configure family settings', 'family', { access: 'staffOnly' }),
  ],
  userphone: [
    cmd('userphone', 'Start a cross-server phone call', 'userphone'),
    cmd('hangup', 'End the current userphone call', 'userphone'),
    cmd('phonebook', 'View your server\'s userphone statistics and recent calls', 'userphone'),
    cmd('userphoneconfig', 'Configure userphone settings', 'userphone', { access: 'adminOnly' }),
  ],
  backup: [
    cmd('backupcreate', 'Create a full backup of the server configuration', 'backup', { access: 'adminOnly' }),
    cmd('backuplist', 'View all server backups', 'backup', { access: 'adminOnly' }),
    cmd('backupinfo', 'View detailed information about a backup', 'backup', { access: 'adminOnly' }),
    cmd('backuprestore', 'Restore the server from a backup', 'backup', { access: 'adminOnly' }),
    cmd('backupcompare', 'Compare a backup against the current server state', 'backup', { access: 'adminOnly' }),
    cmd('backupdelete', 'Delete a server backup', 'backup', { access: 'adminOnly' }),
    cmd('backupconfig', 'Configure backup settings', 'backup', { access: 'adminOnly' }),
  ],
  raffles: [
    cmd('raffle', 'Create a new raffle', 'raffles', { access: 'staffOnly' }),
    cmd('enterraffle', 'Buy tickets for a raffle', 'raffles'),
    cmd('mytickets', 'View your tickets in active raffles', 'raffles'),
    cmd('raffleinfo', 'View raffle details', 'raffles'),
    cmd('endraffle', 'End a raffle early', 'raffles', { access: 'staffOnly' }),
    cmd('cancelraffle', 'Cancel and refund a raffle', 'raffles', { access: 'staffOnly' }),
    cmd('rafflelist', 'List active raffles', 'raffles'),
    cmd('raffle-config', 'Configure raffle settings', 'raffles', { subs: ['view', 'channel', 'ticket-price', 'currency', 'max-tickets', 'max-active', 'dm-winners', 'ping-role', 'color', 'refund-on-cancel'], access: 'adminOnly' }),
  ],
  donationtracking: [
    cmd('donate', 'Donate currency toward a goal', 'donationtracking'),
    cmd('donationleaderboard', 'View top donors', 'donationtracking'),
    cmd('donationprogress', 'View donation progress toward goal', 'donationtracking'),
    cmd('mydonations', 'View your donation history', 'donationtracking'),
    cmd('donationgoal', 'Set/view/clear donation goal', 'donationtracking', { subs: ['set', 'view', 'clear'], access: 'staffOnly' }),
    cmd('donationlist', 'List donation campaigns', 'donationtracking'),
    cmd('donationconfig', 'Configure donation settings', 'donationtracking', { subs: ['view', 'channel', 'currency', 'goal-amount', 'goal-name', 'goal-toggle', 'min-donation', 'max-donation', 'milestone-toggle', 'leaderboard-size', 'color', 'log-channel'], access: 'adminOnly' }),
    cmd('donationreset', 'Reset all donation data', 'donationtracking', { access: 'adminOnly' }),
  ],
  timers: [
    cmd('timer', 'Start a countdown timer', 'timers'),
    cmd('timerlist', 'List your active timers', 'timers'),
    cmd('timercancel', 'Cancel a timer', 'timers'),
    cmd('timercheck', 'Check time remaining on a timer', 'timers'),
    cmd('timerserverlist', 'View all active timers in the server', 'timers', { access: 'staffOnly' }),
    cmd('timerconfig', 'Configure timer settings', 'timers', { subs: ['view', 'max-per-user', 'max-duration', 'notify-channel', 'allow-dm', 'color', 'log-channel'], access: 'adminOnly' }),
  ],
  images: [
    cmd('cat', 'Random cat image', 'images'),
    cmd('dog', 'Random dog image', 'images'),
    cmd('fox', 'Random fox image', 'images'),
    cmd('bird', 'Random bird image', 'images'),
    cmd('panda', 'Random panda image', 'images'),
    cmd('redpanda', 'Random red panda image', 'images'),
    cmd('drake', 'Drake meme format', 'images'),
    cmd('meme', 'Random meme', 'images'),
    cmd('wasted', 'GTA wasted effect on avatar', 'images'),
    cmd('wanted', 'Wanted poster with avatar', 'images'),
    cmd('triggered', 'Triggered effect on avatar', 'images'),
    cmd('blur', 'Blur a user\'s avatar', 'images'),
    cmd('greyscale', 'Greyscale a user\'s avatar', 'images'),
    cmd('invert', 'Invert avatar colors', 'images'),
    cmd('pixelate', 'Pixelate a user\'s avatar', 'images'),
    cmd('mirror', 'Mirror a user\'s avatar', 'images'),
    cmd('avatar', 'View full-size avatar', 'images'),
    cmd('banner', 'View user banner', 'images'),
    cmd('servericon', 'View server icon', 'images'),
    cmd('images-config', 'Configure image settings', 'images', { access: 'staffOnly' }),
  ],
  utilities: [
    cmd('google', 'Search Google', 'utilities'),
    cmd('youtube', 'Search YouTube', 'utilities'),
    cmd('github', 'Search GitHub repos', 'utilities'),
    cmd('npm', 'Search NPM packages', 'utilities'),
    cmd('steam', 'Search Steam games', 'utilities'),
    cmd('weather', 'Get weather forecast', 'utilities'),
    cmd('crypto', 'Cryptocurrency prices', 'utilities'),
    cmd('translate', 'Translate text', 'utilities'),
    cmd('color', 'Color preview', 'utilities'),
    cmd('calculator', 'Math calculator', 'utilities'),
    cmd('qrcode', 'Generate QR code', 'utilities'),
    cmd('password', 'Generate password', 'utilities'),
    cmd('encode', 'Base64 encode', 'utilities'),
    cmd('decode', 'Base64 decode', 'utilities'),
    cmd('emojify', 'Convert text to emojis', 'utilities'),
    cmd('enlarge', 'Enlarge a custom emoji', 'utilities'),
    cmd('anagram', 'Find anagrams', 'utilities'),
    cmd('minecraft', 'Minecraft server status', 'utilities'),
    cmd('poll', 'Create a quick poll', 'utilities'),
    cmd('notepad-add', 'Add a note', 'utilities'),
    cmd('notepad-view', 'View your notes', 'utilities'),
    cmd('notepad-edit', 'Edit a note', 'utilities'),
    cmd('notepad-delete', 'Delete a note', 'utilities'),
    cmd('utilities-config', 'Configure utility settings', 'utilities', { access: 'staffOnly' }),
  ],
  soundboard: [
    cmd('soundboard-play', 'Play a sound effect', 'soundboard'),
    cmd('soundboard-list', 'List available sounds', 'soundboard'),
    cmd('soundboard-random', 'Play a random sound', 'soundboard'),
    cmd('soundboard-add', 'Add a custom sound', 'soundboard'),
    cmd('soundboard-remove', 'Remove a sound', 'soundboard'),
    cmd('soundboard-rename', 'Rename a sound', 'soundboard'),
    cmd('soundboard-config', 'Configure soundboard settings', 'soundboard', { access: 'staffOnly' }),
  ],
  autosetup: [
    cmd('autosetup-logs', 'Auto-setup logging channels', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-welcome', 'Auto-setup welcome system', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-tickets', 'Auto-setup ticket system', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-fun', 'Auto-setup fun channels', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-music', 'Auto-setup music channels', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-moderation', 'Auto-setup moderation', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-leveling', 'Auto-setup leveling system', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-all', 'Run all setup wizards', 'autosetup', { access: 'staffOnly' }),
    cmd('autosetup-config', 'Configure autosetup settings', 'autosetup', { access: 'staffOnly' }),
  ],
};

export function getCommandsForModule(moduleKey: string): CommandDef[] {
  return COMMAND_REGISTRY[moduleKey] ?? [];
}

export const DEFAULT_ACCESS_LABELS: Record<DefaultAccess, string> = {
  everyone: 'Everyone',
  staffOnly: 'Staff Only',
  adminOnly: 'Admin Only',
  ownerOnly: 'Server Owner',
};
