import {
  SlashCommandBuilder,
  ChatInputCommandInteraction,
  AttachmentBuilder,
} from 'discord.js';
import type { BotCommand } from '../../../../Shared/src/types/command';
import { isTicketChannel, generateTranscript } from '../../helpers';
import { moduleConfig } from '../../../../Shared/src/middleware/moduleConfig';
import { Colors, successEmbed, errorEmbed } from '../../../../Shared/src/utils/embed';

const command: BotCommand = {
  module: 'tickets',
  permissionPath: 'tickets.transcript',
  data: new SlashCommandBuilder()
    .setName('transcript')
    .setDescription('Generate a transcript of the current ticket'),

  async execute(interaction: ChatInputCommandInteraction) {
    if (!interaction.guildId || !interaction.guild || !interaction.channel) {
      return interaction.reply({
        content: '❌ This command can only be used in a server.',
        ephemeral: true,
      });
    }

    const _cfgResult = await moduleConfig.getModuleConfig(interaction.guildId!, 'tickets');
    const config = (_cfgResult?.config ?? {}) as any;

    if (!config?.enabled) {
      return interaction.reply({
        content: '❌ The tickets module is not enabled on this server.',
        ephemeral: true,
      });
    }

    // Check if transcripts are enabled
    if (!config.transcriptEnabled) {
      return interaction.reply({
        content: '❌ Transcripts are not enabled. An admin can enable them with `/ticket-config transcript-toggle`',
        ephemeral: true,
      });
    }

    // Check if this is a ticket channel
    const ticketData = await isTicketChannel(interaction.guildId!, interaction.channel.id);
    if (!ticketData) {
      return interaction.reply({
        content: '❌ This command can only be used in a ticket channel.',
        ephemeral: true,
      });
    }

    await interaction.deferReply({ ephemeral: true });

    try {
      // Generate transcript
      const transcript = await generateTranscript(interaction.channel.id, interaction.guild);

      if (!transcript) {
        return interaction.editReply({
          content: '❌ Failed to generate transcript.',
        });
      }

      // Create attachment
      const fileName = `ticket-${ticketData.ticketNumber}-${Date.now()}.html`;
      const attachment = new AttachmentBuilder(Buffer.from(transcript), {
        name: fileName,
      });

      // Send reply with attachment
      await interaction.editReply({
        content: '✅ Transcript generated successfully!',
        files: [attachment],
      });

      // Post to transcript channel if configured
      if (config.transcriptChannelId) {
        try {
          const transcriptChannel = await interaction.guild.channels.fetch(
            config.transcriptChannelId
          );
          if (transcriptChannel && transcriptChannel.isTextBased()) {
            await transcriptChannel.send({
              content: `Transcript for Ticket #${ticketData.ticketNumber} - Generated by <@${interaction.user.id}>`,
              files: [new AttachmentBuilder(Buffer.from(transcript), { name: fileName })],
            });
          }
        } catch (error) {
          console.error('[Tickets] Failed to post transcript to log channel:', error);
        }
      }
    } catch (error) {
      console.error('[Tickets] Error generating transcript:', error);
      return interaction.editReply({
        content: '❌ An error occurred while generating the transcript.',
      });
    }
  },
};

export default command;
